// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7DKnsKGJ03HRbtbjfBL9BgVzzdIJghLQ',
    appId: '1:812774997300:web:4a73bb149aec57dbb4b961',
    messagingSenderId: '812774997300',
    projectId: 'healthiin',
    authDomain: 'healthiin.firebaseapp.com',
    storageBucket: 'healthiin.appspot.com',
    measurementId: 'G-9K1YQD0J3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgcZxOcOp-o3tzodjrC8sbmoJS2OMx2jQ',
    appId: '1:812774997300:android:f54fc34659e0796bb4b961',
    messagingSenderId: '812774997300',
    projectId: 'healthiin',
    storageBucket: 'healthiin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRvGtPWJfxjm1ihZ1hMStbvi9npbBk22k',
    appId: '1:812774997300:ios:eee3ee044eadb020b4b961',
    messagingSenderId: '812774997300',
    projectId: 'healthiin',
    storageBucket: 'healthiin.appspot.com',
    androidClientId:
        '812774997300-ssr1q1d8m9d0ukcjdrbduslevu31vv17.apps.googleusercontent.com',
    iosClientId:
        '812774997300-03t8m3p0ccekt72mvdtugqnq84c6j0k3.apps.googleusercontent.com',
    iosBundleId: 'com.example.heathin',
  );
}
